# All env variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams
env:
  tracing:
    exportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
  auth:
    clientId: ${AXON_UI_CLIENT_ID:client-id}
    clientSecret: ${AXON_UI_CLIENT_SECRET:client-secret}
  wsm:
    basePath: ${WSM_ADDRESS:https://terra-devel-wsm.api.verily.com}
  sam:
    basePath: ${SAM_ADDRESS:https://terra-devel-sam.api.verily.com}
    resourceId: ${SAM_RESOURCE_ID:axonserver-dev}
  calhoun:
    basePath: ${CALHOUN_ADDRESS:https://terra-devel-calhoun.api.verily.com}

# Below here is non-deployment-specific

# When the target is 'local' the write-config.sh script will generate this properties file. It
# contains the configuration of the BPM test application. We can use that application in our
# integration testing to make sure the application code paths are working. However, we do not
# want it to appear in production environments.
spring.config.import: optional:file:../config/local-properties.yml

logging.pattern.level: "%X{requestId} %5p"

server:
  compression:
    enabled: true
    mimeTypes: text/css,application/javascript
  port: 8080

spring:
  application.name: axonserver
  web:
    resources:
      cache:
        cachecontrol:
          maxAge: 0
          mustRevalidate: true
        useLastModified: false
      staticLocations: classpath:/api/

axonserver:
  status-check:
    enabled: true
    pollingIntervalSeconds: 60
    startupWaitSeconds: 5
    stalenessThresholdSeconds: 125
  auth:
    clientId: ${env.auth.clientId}
    clientSecret: ${env.auth.clientSecret}
  wsm:
    basePath: ${env.wsm.basePath}
  sam:
    basePath: ${env.sam.basePath}
    resourceId: ${env.sam.resourceId}
  calhoun:
    basePath: ${env.calhoun.basePath}

terra.common:
  kubernetes:
    inKubernetes: false

  tracing:
    stackdriverExportEnabled: ${env.tracing.exportEnabled}
    samplingRate: ${env.tracing.samplingRate}
